# Generated by Django 5.1.2 on 2024-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studnet',
            fields=[
                ('student_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=25)),
                ('student_dept', models.CharField(max_length=3)),
            ],
        ),
    ]
