# Generated by Django 5.1.2 on 2024-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_temp', '0002_studnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
