# Generated by Django 5.1.2 on 2024-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_temp', '0003_rename_studnet_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dept',
            field=models.CharField(choices=[('cs', 'CS'), ('is', 'IS'), ('it', 'IT'), ('cys', 'CYS'), ('ds', 'DS'), ('ai', 'AI')], default='cys', max_length=3),
        ),
    ]
